### ISSUE TITLE
statsmodels upgrade

### ISSUE THREAD

**Issue by jabbera** [goldmansachs/gs-quant#233]
**Describe the problem.**
statsmodels < 13 can't be installed with scipy >= 1.8.0: https://stackoverflow.com/questions/71106940/cannot-import-name-centered-from-scipy-signal-signaltools

This is a valid configuration per this projects setup.py:

https://github.com/goldmansachs/gs-quant/blob/1272790ae3eb43819f80a0ad5053a36b349e9a3d/setup.py#L76-L77

Repro:
```
python3 -m venv .venv
source .venv/bin/activate
pip install gs-quant
python -c "from statsmodels.api import DLS"
```

Traceback:
```
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jabbera/stats/.venv/lib/python3.8/site-packages/statsmodels/api.py", line 27, in <module>
    from .tsa import api as tsa
  File "/home/jabbera/stats/.venv/lib/python3.8/site-packages/statsmodels/tsa/api.py", line 31, in <module>
    from .filters import api as filters
  File "/home/jabbera/stats/.venv/lib/python3.8/site-packages/statsmodels/tsa/filters/api.py", line 6, in <module>
    from .filtertools import miso_lfilter, convolution_filter, recursive_filter
  File "/home/jabbera/stats/.venv/lib/python3.8/site-packages/statsmodels/tsa/filters/filtertools.py", line 18, in <module>
    from scipy.signal.signaltools import _centered as trim_centered
ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (/home/jabbera/stats/.venv/lib/python3.8/site-packages/scipy/signal/signaltools.py)
```

**Describe the solution you'd like**
Remove the requirement for statsmodels < 13. I really don't want to be pinned to scipy < 1.8.0

**Describe alternatives you've considered**
Downgrade scipy.

**Are you willing to contribute**
Need to check with my legal department.

**Comment by theavey** [comment]
Agree that this is an issue. Would be at least nice to know why the `statsmodels` version is capped

**Comment by S-Manglik** [comment]
Statsmodels is now unpinned and we are working on unpinning scipy.
